Alert-in-body element created
NYCOpportunity/growingupnyc-patterns pull request #10
Opened 2020-09-29 15:25 UTC by yone920

Alert-in-body element created.

2020-09-30 17:37 UTC, kimpenguin commented on src/elements/alert-in-body/alert-in-body.scss
> +.alert-in-body {
@yone920 instead of `.alert-in-body`, could we rename the class to `.alert`?

2020-09-30 17:40 UTC, kimpenguin requested changes
@yone920 Looks good. Could you adjust the class name and also try to see if there is any styling adjustments you might want to make based on the `head_extras` in the twig files in the core? There's some template specific styling. Maybe the padding could be set with tailwind classes?

2020-10-02 14:01 UTC, yone920 commented
> @yone920 Looks good. Could you adjust the class name and also try to see if there is any styling adjustments you might want to make based on the `head_extras` in the twig files in the core? There's some template specific styling. Maybe the padding could be set with tailwind classes?

I have included the styling on the head_extras to the 'alert-in-body.scss. I am not if you refering the styles in the head-extra.

2020-10-02 14:56 UTC, kimpenguin commented
@yone920 Could you also rename the slm files and element files to alert for consistency?

The head_extras are the .alert styling on some of the twig files in the core. It's wrapped within on some of the single.twig an archive.twig files`{% block head_extras %}{% endblock %}`. We would remove those in-template stylings to use this pattern.

2020-10-14 20:46 UTC, kimpenguin approved these changes

2020-10-16 13:18 UTC, yone920 commented
Merged to Main.

2020-10-16 13:18 UTC, closed without merging